word_list = [
    "apple", "banana", "grapefruit", "mango", "pineapple", "strawberry",
    "blueberry", "raspberry", "blackberry", "cherry", "watermelon", "cantaloupe",
    "honeydew", "kiwi", "papaya", "pomegranate", "apricot", "peach", "plum",
    "nectarine", "tangerine", "clementine", "lime", "lemon", "orange",
    "avocado", "coconut", "date", "fig", "guava", "lychee", "passionfruit",
    "persimmon", "pinecone", "quince", "starfruit", "dragonfruit",
    "jackfruit", "durian", "elderberry", "gooseberry", "mulberry",
    "boysenberry", "cranberry", "currant", "kumquat", "loquat", "salmonberry",
    "tomato", "potato", "cucumber", "zucchini", "squash", "pumpkin",
    "carrot", "beet", "radish", "turnip", "parsnip", "lettuce",
    "spinach", "kale", "broccoli", "cauliflower", "cabbage", "brusselsprout",
    "asparagus", "artichoke", "celery", "bellpepper", "jalapeno", "habanero",
    "ghostpepper", "onion", "garlic", "ginger", "shallot", "scallion",
    "chives", "cilantro", "parsley", "basil", "oregano", "thyme",
    "rosemary", "sage", "mint", "dill", "tarragon", "bayleaf",
    "fennel", "lemongrass", "marjoram", "paprika", "saffron", "turmeric",
    "cinnamon", "nutmeg", "clove", "cardamom", "allspice", "anise",
    "coriander", "cumin", "mustard", "pepper", "vanilla", "cocoa",
    "coffee", "tea", "milk", "cheese", "butter", "yogurt",
    "cream", "icecream", "sourcream", "whippedcream", "custard", "pudding",
    "chocolate", "candy", "cookie", "cake", "brownie", "pie",
    "tart", "pastry", "muffin", "bagel", "donut", "croissant",
    "sandwich", "burger", "pizza", "pasta", "lasagna", "spaghetti",
    "ravioli", "tortellini", "gnocchi", "fettuccine", "macaroni", "noodle",
    "ramen", "soba", "udon", "pho", "springroll", "dumpling",
    "sushi", "tempura", "teriyaki", "wasabi", "sashimi", "nigiri",
    "edamame", "miso", "tofu", "kimchi", "bibimbap", "bulgogi",
    "ramyun", "bento", "katsu", "yakitori", "sukiyaki", "shabu",
    "hotpot", "fondue", "quiche", "souffle", "omelette", "frittata",
    "pancake", "waffle", "crepe", "blintz", "churro", "scone",
    "biscuit", "brioche", "babka", "strudel", "empanada", "samosa",
    "pakora", "bhaji", "korma", "biryani", "tikka", "naan",
    "roti", "chapati", "paratha", "pita", "tortilla", "quesadilla",
    "enchilada", "taco", "burrito", "fajita", "chimichanga", "tamale",
    "guacamole", "salsa", "ceviche", "paella", "gazpacho", "ratatouille",
    "bouillabaisse", "cassoulet", "coqauvin", "bolognese", "carbonara", "alfredo",
    "marinara", "pesto", "bechamel", "roux", "consomme", "bisque",
    "gumbo", "jambalaya", "etouffee", "cioppino", "chowder", "minestrone",
    "gazelle", "giraffe", "hippopotamus", "elephant", "rhinoceros", "crocodile",
    "alligator", "kangaroo", "koala", "platypus", "dolphin", "whale",
    "shark", "octopus", "squid", "lobster", "crab", "jellyfish",
    "starfish", "seahorse", "urchin", "coral", "anemone", "barnacle",
    "clam", "oyster", "mussel", "scallop", "snail", "slug",
    "beetle", "ant", "bee", "wasp", "hornet", "dragonfly",
    "butterfly", "moth", "grasshopper", "cricket", "locust", "katydid",
    "cockroach", "termite", "earwig", "silverfish", "firefly", "lightningbug",
    "mosquito", "gnat", "flea", "tick", "louse", "mite",
    "spider", "tarantula", "scorpion", "centipede", "millipede", "worm",
    "leech", "earthworm", "tapeworm", "roundworm", "hookworm", "flatworm",
    "nematode", "planarian", "fluke", "annelid", "polychaete", "brittle",
    "star", "bivalve", "gastropod", "cephalopod", "arachnid", "arthropod",
    "mollusk", "cnidarian", "echinoderm", "platyhelminth", "nematoda", "annelida",
    "coelenterate", "porifera", "chordate", "vertebrate", "invertebrate", "amphibian",
    "reptile", "mammal", "bird", "fish", "crustacean", "insect"
]
